"""Radar format adapters and normalized polar-volume publication."""

from .attenuation import (
    AttenuationApplicabilityConfig,
    AttenuationCoefficientConfig,
    AttenuationInputError,
    AttenuationProfile,
    AttenuationRayResult,
    AttenuationSweepResult,
    build_attenuation_artifact,
    load_attenuation_profile,
    process_kdp_attenuation_ray,
    process_kdp_attenuation_sweep,
)
from .calibration import (
    CalibrationInputError,
    CalibrationProfile,
    CalibrationReferenceManifest,
    CalibrationReferencePolicy,
    CoefficientTable,
    CoefficientTableEntry,
    ResolvedAttenuationCoefficients,
    load_calibration_profile,
    load_calibration_reference_manifest,
    load_coefficient_table,
    resolve_attenuation_coefficients,
)
from .config import FieldMapping, RadarDecoderConfig, load_radar_config
from .fmt import DECODER_VERSION, DecodedRadarVolume, DecodeError, decode_fmt_volume
from .health import (
    RadarHealthConfig,
    RadarHealthSummary,
    assess_volume_health,
    load_radar_health_config,
)
from .phase_processing import (
    PhaseProcessingInputError,
    PhaseProcessingProfile,
    PhaseProcessingRayResult,
    PhaseProcessingSweepResult,
    build_phase_processing_artifact,
    load_phase_processing_profile,
    process_phidp_ray,
    process_phidp_sweep,
)
from .qc import BasicQCProfile, QCInputError, QCResult, apply_basic_qc, load_qc_profile
from .qc_zarr import build_qc_zarr_store, validate_qc_zarr_store
from .zarr_volume import build_zarr_store, validate_zarr_store, write_zarr_store

__all__ = [
    "DECODER_VERSION",
    "DecodeError",
    "DecodedRadarVolume",
    "AttenuationApplicabilityConfig",
    "AttenuationCoefficientConfig",
    "AttenuationInputError",
    "AttenuationProfile",
    "AttenuationRayResult",
    "AttenuationSweepResult",
    "CalibrationInputError",
    "CalibrationProfile",
    "CalibrationReferenceManifest",
    "CalibrationReferencePolicy",
    "CoefficientTable",
    "CoefficientTableEntry",
    "FieldMapping",
    "PhaseProcessingInputError",
    "PhaseProcessingProfile",
    "PhaseProcessingRayResult",
    "PhaseProcessingSweepResult",
    "RadarDecoderConfig",
    "RadarHealthConfig",
    "RadarHealthSummary",
    "BasicQCProfile",
    "QCInputError",
    "QCResult",
    "ResolvedAttenuationCoefficients",
    "apply_basic_qc",
    "build_attenuation_artifact",
    "build_qc_zarr_store",
    "assess_volume_health",
    "build_phase_processing_artifact",
    "build_zarr_store",
    "decode_fmt_volume",
    "load_attenuation_profile",
    "load_calibration_profile",
    "load_calibration_reference_manifest",
    "load_coefficient_table",
    "load_radar_config",
    "load_radar_health_config",
    "load_phase_processing_profile",
    "load_qc_profile",
    "process_kdp_attenuation_ray",
    "process_kdp_attenuation_sweep",
    "process_phidp_ray",
    "process_phidp_sweep",
    "resolve_attenuation_coefficients",
    "validate_qc_zarr_store",
    "validate_zarr_store",
    "write_zarr_store",
]
