const {test}=require('node:test'); const assert=require('node:assert/strict');
const m=require(process.env.OPS_MODEL_JS), d=require(process.env.OPS_MONITORING_JS);
const id='10000000-0000-0000-0000-000000000001', time='2026-09-23T00:00:00Z';
const task=(override={})=>({state:'RUNNING',current_attempt:id,attempts:[{id,queued_at:time,started_at:'2026-09-23T00:00:05Z',finished_at:'2026-09-23T00:00:15Z'}],...override});
test('attempt queue and elapsed use separate database timestamps',()=>{const v=m.taskTiming(task());assert.equal(v.queue,5000);assert.equal(v.elapsed,10000)});
test('retry timings use current attempt and retain old attempt history',()=>{const t=task();t.attempts.unshift({id:'old',queued_at:'2026-09-22T00:00:00Z',started_at:'2026-09-22T01:00:00Z'});assert.equal(m.taskTiming(t).queue,5000)});
test('dispatch time cannot substitute missing queued_at',()=>{const t=task();delete t.attempts[0].queued_at;t.dispatched_at=time;assert.equal(m.taskTiming(t).queue,null)});
test('queued but not claimed shows a known wait',()=>assert.equal(m.taskTiming({state:'QUEUED',queued_at:time,attempts:[]},Date.parse(time)+12000).queue,12000));
test('unknown enqueue time stays unknown even while queued',()=>assert.equal(m.taskTiming({state:'QUEUED',attempts:[]},Date.parse(time)).queue,null));
test('negative queue duration is not clamped into zero',()=>{const t=task();t.attempts[0].queued_at='2026-09-23T01:00:00Z';assert.equal(m.taskTiming(t).queue,null)});
test('zero queue duration is a legitimate measurement',()=>{const t=task();t.attempts[0].queued_at=t.attempts[0].started_at;assert.equal(m.taskTiming(t).queue,0)});
test('unknown finished time uses current clock only for running display',()=>{const t=task();t.attempts[0].finished_at=null;assert.equal(m.taskTiming(t,Date.parse(time)+16000).elapsed,11000)});
test('data deep link roundtrips UUID without constructing an object path',()=>{const url=m.viewURL({page:'data',scan:id});assert.equal(m.viewFromSearch(url.split('?')[1]).scan,id)});
test('selected scan links only to a one minute preflight window',()=>{assert.deepEqual(d.scanWindow({observed_at:'2026-09-23T00:01:35.800Z'}),{start:'2026-09-23T00:01:00.000Z',end:'2026-09-23T00:02:00.000Z'})});
test('preflight navigation retains UTC interval and preset',()=>{const v={page:'new',radar:'z9591',preset:'render_only',...d.scanWindow({observed_at:time})};const restored=m.viewFromSearch(m.viewURL(v).split('?')[1]);for(const key of Object.keys(v))assert.equal(restored[key],v[key])});
test('naive time and illegal preset are not restored from URL',()=>{const v=m.viewFromSearch('?view=new&start=2026-09-23T00:00:00&preset=delete&radar=../../etc');assert.equal(v.start,undefined);assert.equal(v.preset,undefined);assert.equal(v.radar,undefined)});
test('marker result for old pointer is not shown as current',()=>assert.equal(d.currentCheck([{stage:'qc',uri:'s3://b/old',state:'marker_checked'}],'qc','s3://b/new'),null));
test('marker result binds to stage and exact URI',()=>{const c={stage:'qc',uri:'s3://b/new'};assert.equal(d.currentCheck([c],'qc',c.uri),c);assert.equal(d.currentCheck([c],'grid',c.uri),null)});
test('draining with active lease is not reported empty',()=>assert.equal(d.poolState({mode:'DRAINING',active:1,stalled:1,ready:1}),'排空中'));
test('drained remains paused even when a ready worker registers',()=>assert.equal(d.poolState({mode:'DRAINING',active:0,ready:2}),'已暂停接单'));
test('accepting without a ready worker is not a ready pool',()=>assert.equal(d.poolState({mode:'ACCEPTING',active:0,ready:0}),'没有可用 Worker'));
test('idle worker observes pool pause',()=>assert.equal(m.workerState({seen_at:time,ready:true,busy:false,pool_mode:'DRAINING'},Date.parse(time)+1000),'执行池暂停接单'));
test('active worker remains active during pool drain',()=>assert.equal(m.workerState({seen_at:time,ready:true,busy:true,pool_mode:'DRAINING'},Date.parse(time)+1000),'正在执行'));
for(const seen_at of ['invalid','2026-09-23T01:00:00Z'])test('invalid/future heartbeat is not healthy '+seen_at,()=>assert.equal(m.workerState({seen_at,ready:true,busy:false},Date.parse(time)),'心跳时间异常'));
test('UTC+8 input windows preserve half-open bounds',()=>assert.deepEqual(d.windowQuery('2026-09-23T08:00','2026-09-23T09:00',24),{start:'2026-09-23T00:00:00.000Z',end:'2026-09-23T01:00:00.000Z'}));
for(const value of ['2026-02-30T09:00','2026-09-23T24:00','2026-09-23T10:61','bad'])test('impossible calendar time rejected '+value,()=>assert.throws(()=>m.toUTC(value)));
test('window limit rejects reversed, excess or invalid budget',()=>{assert.throws(()=>d.windowQuery('2026-09-23T09:00','2026-09-23T08:00',24));assert.throws(()=>d.windowQuery('2026-09-23T09:00','2026-09-25T08:00',24));assert.throws(()=>d.windowQuery('2026-09-23T09:00','2026-09-23T10:00',NaN))});
test('zero and missing quantiles remain visibly distinct',()=>{assert.equal(m.duration(0),'0 ms');assert.equal(m.duration(null),'未采集');assert.equal(m.bytes(undefined),'未采集')});
test('performance route survives reload',()=>assert.equal(m.viewFromSearch('?view=performance').page,'performance'));
